logging:
  level:
    org.springframework.security: INFO
    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.client: DEBUG

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 20000

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/