spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/food
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

#camunda:
#  bpm:
#    run.cors:
#      enabled: true
#    admin-user:
#      password: demo
#      id: demo
#      first-name: Demo
#      last-name: Demo
#    database:
#      schema-name: camunda

rabbitmq:
  topic-exchange-food: food.notify.exchange
  routing-key-food: key.food

server:
  error:
    include-message: always
  port: 8081