spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: food-service
          uri: http://food-service:8081
          predicates:
            - Path=/food/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - RewritePath=/food/(?<path>.*), /$\{path}

server:
  port: 8989