spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: "[classpath:/, classpath:/services, classpath:/services/{application}]"
  profiles:
    active: native
  security:
    user:
      password: sa

server:
  port: 8001